function displayPoem(response) {
  console.log("poem generated");
  new Typewriter("#poem", {
    strings: response.data.answer,
    autoStart: true,
    delay: 1,
    cursor: "",
  });
}

function generatePoem(event) {
  event.preventDefault();
  let instructionsInput = document.querySelector("#user-instructions");
  let apiKey = "5a66ffb09c7a4o246a78be8f021tfdd3";
  let context =
    "You are an inspirational and romantic poem expert who is very adept in writing short poems. Your mission is to generate a 4-6 line poem in basic HTML. Make sure to follow the user instructions. Sign the poem at the end with 'Generated by SheCodes AI but inspired by Dana Paulette ❤️' and between a <strong> element.";
  let prompt = `User Instructions:  Generate an inspirational poem about ${instructionsInput.value}`;
  let apiUrl = `https://api.shecodes.io/ai/v1/generate?prompt=${prompt}&context=${context}&key=${apiKey}`;

  console.log(`Prompt: ${prompt} and Context: ${context}`);
  console.log("Generating poem");

  axios.get(apiUrl).then(displayPoem);
}
let poemFormElement = document.querySelector("#poem-generator-form");
poemFormElement.addEventListener("submit", generatePoem);
